
package view.QuanLyDonHang;

/**
 *
 * @author NANG TIEN HANH
 */
public class jframe_ThemDonHang extends javax.swing.JFrame {

    /**
     * Creates new form jframe_ThemDonHang
     */
    public jframe_ThemDonHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_Root = new view.panelBackgpround();
        jpanel_ThanhToan = new javax.swing.JPanel();
        jradiobutton_TienMat = new javax.swing.JRadioButton();
        jradiobutton_ChuyenKhoan = new javax.swing.JRadioButton();
        jbutton_ThanhToan = new javax.swing.JButton();
        jlable_HinhThucTT = new javax.swing.JLabel();
        jpanel_BangSP = new javax.swing.JPanel();
        jscrollpane_BangSP = new javax.swing.JScrollPane();
        jtable_BangSP = new javax.swing.JTable();
        jbutton_ThemSP = new javax.swing.JButton();
        jbutton_XoaSP = new javax.swing.JButton();
        jbutton_ChinhSuaSP = new javax.swing.JButton();
        jlable_MaDH = new javax.swing.JLabel();
        jpanel_DieuKhien = new javax.swing.JPanel();
        jpanel_Search = new javax.swing.JPanel();
        jtextfield_Search = new javax.swing.JTextField();
        jlable_Search = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanel_ThanhToan.setBackground(new java.awt.Color(255, 255, 255));

        jradiobutton_TienMat.setFont(new java.awt.Font("UTM Helve", 1, 13)); // NOI18N
        jradiobutton_TienMat.setText("Tiền mặt");
        jradiobutton_TienMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradiobutton_TienMatActionPerformed(evt);
            }
        });

        jradiobutton_ChuyenKhoan.setFont(new java.awt.Font("UTM Helve", 1, 13)); // NOI18N
        jradiobutton_ChuyenKhoan.setText("Chuyển khoản");
        jradiobutton_ChuyenKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradiobutton_ChuyenKhoanActionPerformed(evt);
            }
        });

        jbutton_ThanhToan.setBackground(new java.awt.Color(94, 42, 14));
        jbutton_ThanhToan.setFont(new java.awt.Font("UTM Helve", 1, 14)); // NOI18N
        jbutton_ThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        jbutton_ThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thanh-toan.png"))); // NOI18N
        jbutton_ThanhToan.setText("Thanh toán");
        jbutton_ThanhToan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_ThanhToanActionPerformed(evt);
            }
        });

        jlable_HinhThucTT.setBackground(new java.awt.Color(255, 204, 204));
        jlable_HinhThucTT.setFont(new java.awt.Font("UTM Helve", 1, 14)); // NOI18N
        jlable_HinhThucTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlable_HinhThucTT.setText("Hình thức thanh toán");
        jlable_HinhThucTT.setAlignmentX(0.5F);
        jlable_HinhThucTT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlable_HinhThucTT.setOpaque(true);

        javax.swing.GroupLayout jpanel_ThanhToanLayout = new javax.swing.GroupLayout(jpanel_ThanhToan);
        jpanel_ThanhToan.setLayout(jpanel_ThanhToanLayout);
        jpanel_ThanhToanLayout.setHorizontalGroup(
            jpanel_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_ThanhToanLayout.createSequentialGroup()
                .addGroup(jpanel_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_ThanhToanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlable_HinhThucTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpanel_ThanhToanLayout.createSequentialGroup()
                        .addGroup(jpanel_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_ThanhToanLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jpanel_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jradiobutton_TienMat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jradiobutton_ChuyenKhoan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                            .addGroup(jpanel_ThanhToanLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbutton_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpanel_ThanhToanLayout.setVerticalGroup(
            jpanel_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_ThanhToanLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlable_HinhThucTT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jradiobutton_TienMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jradiobutton_ChuyenKhoan)
                .addGap(18, 18, 18)
                .addComponent(jbutton_ThanhToan)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        jpanel_BangSP.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_BangSP.setPreferredSize(new java.awt.Dimension(765, 300));

        jscrollpane_BangSP.setBackground(new java.awt.Color(255, 204, 204));
        jscrollpane_BangSP.setFont(new java.awt.Font("UTM Helve", 1, 14)); // NOI18N

        jtable_BangSP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jtable_BangSP.setFont(new java.awt.Font("UTM Helve", 0, 14)); // NOI18N
        jtable_BangSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", null, null},
                {"", "", "", null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ SẢN PHẨM", "TÊN SẢN PHẨM", "ĐƠN VỊ TÍNH", "SỐ LƯỢNG", "ĐƠN GIÁ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtable_BangSP.getTableHeader().setResizingAllowed(false);
        jtable_BangSP.getTableHeader().setReorderingAllowed(false);
        jscrollpane_BangSP.setViewportView(jtable_BangSP);

        jbutton_ThemSP.setBackground(new java.awt.Color(94, 42, 14));
        jbutton_ThemSP.setFont(new java.awt.Font("UTM Helve", 1, 14)); // NOI18N
        jbutton_ThemSP.setForeground(new java.awt.Color(255, 255, 255));
        jbutton_ThemSP.setText("Thêm sản phẩm");
        jbutton_ThemSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton_ThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_ThemSPActionPerformed(evt);
            }
        });

        jbutton_XoaSP.setBackground(new java.awt.Color(147, 94, 64));
        jbutton_XoaSP.setFont(new java.awt.Font("UTM Helve", 1, 14)); // NOI18N
        jbutton_XoaSP.setForeground(new java.awt.Color(255, 255, 255));
        jbutton_XoaSP.setText("Xóa sản phẩm");
        jbutton_XoaSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton_XoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_XoaSPActionPerformed(evt);
            }
        });

        jbutton_ChinhSuaSP.setBackground(new java.awt.Color(177, 137, 101));
        jbutton_ChinhSuaSP.setFont(new java.awt.Font("UTM Helve", 1, 14)); // NOI18N
        jbutton_ChinhSuaSP.setForeground(new java.awt.Color(255, 255, 255));
        jbutton_ChinhSuaSP.setText("Chỉnh sửa");
        jbutton_ChinhSuaSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton_ChinhSuaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_ChinhSuaSPActionPerformed(evt);
            }
        });

        jlable_MaDH.setBackground(new java.awt.Color(255, 204, 204));
        jlable_MaDH.setFont(new java.awt.Font("UTM Helve", 1, 14)); // NOI18N
        jlable_MaDH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlable_MaDH.setText("Mã đơn hàng");
        jlable_MaDH.setAlignmentX(0.5F);
        jlable_MaDH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlable_MaDH.setOpaque(true);

        javax.swing.GroupLayout jpanel_BangSPLayout = new javax.swing.GroupLayout(jpanel_BangSP);
        jpanel_BangSP.setLayout(jpanel_BangSPLayout);
        jpanel_BangSPLayout.setHorizontalGroup(
            jpanel_BangSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_BangSPLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpanel_BangSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpanel_BangSPLayout.createSequentialGroup()
                        .addComponent(jlable_MaDH, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbutton_ThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jbutton_XoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jbutton_ChinhSuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jscrollpane_BangSP, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_BangSPLayout.setVerticalGroup(
            jpanel_BangSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_BangSPLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpanel_BangSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutton_ThemSP)
                    .addComponent(jbutton_XoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton_ChinhSuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlable_MaDH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jscrollpane_BangSP, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jpanel_DieuKhien.setBackground(new java.awt.Color(255, 255, 204));
        jpanel_DieuKhien.setOpaque(false);
        jpanel_DieuKhien.setPreferredSize(new java.awt.Dimension(765, 150));

        jpanel_Search.setOpaque(false);

        jtextfield_Search.setText("Search");
        jtextfield_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_SearchActionPerformed(evt);
            }
        });

        jlable_Search.setBackground(new java.awt.Color(255, 255, 255));
        jlable_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jlable_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlable_Search.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlable_Search.setOpaque(true);

        javax.swing.GroupLayout jpanel_SearchLayout = new javax.swing.GroupLayout(jpanel_Search);
        jpanel_Search.setLayout(jpanel_SearchLayout);
        jpanel_SearchLayout.setHorizontalGroup(
            jpanel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_SearchLayout.createSequentialGroup()
                .addComponent(jtextfield_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jlable_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jpanel_SearchLayout.setVerticalGroup(
            jpanel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_SearchLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpanel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlable_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextfield_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpanel_DieuKhienLayout = new javax.swing.GroupLayout(jpanel_DieuKhien);
        jpanel_DieuKhien.setLayout(jpanel_DieuKhienLayout);
        jpanel_DieuKhienLayout.setHorizontalGroup(
            jpanel_DieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_DieuKhienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(414, 414, 414))
        );
        jpanel_DieuKhienLayout.setVerticalGroup(
            jpanel_DieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_DieuKhienLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jpanel_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpanel_RootLayout = new javax.swing.GroupLayout(jpanel_Root);
        jpanel_Root.setLayout(jpanel_RootLayout);
        jpanel_RootLayout.setHorizontalGroup(
            jpanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_RootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel_DieuKhien, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(jpanel_RootLayout.createSequentialGroup()
                        .addComponent(jpanel_BangSP, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpanel_ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpanel_RootLayout.setVerticalGroup(
            jpanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_RootLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jpanel_DieuKhien, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpanel_BangSP, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanel_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel_Root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel_Root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfield_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_SearchActionPerformed

    private void jbutton_ThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_ThemSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton_ThemSPActionPerformed

    private void jbutton_XoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_XoaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton_XoaSPActionPerformed

    private void jbutton_ChinhSuaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_ChinhSuaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton_ChinhSuaSPActionPerformed

    private void jbutton_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_ThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton_ThanhToanActionPerformed

    private void jradiobutton_TienMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradiobutton_TienMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradiobutton_TienMatActionPerformed

    private void jradiobutton_ChuyenKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradiobutton_ChuyenKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradiobutton_ChuyenKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_ThemDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_ThemDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_ThemDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_ThemDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_ThemDonHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbutton_ChinhSuaSP;
    private javax.swing.JButton jbutton_ThanhToan;
    private javax.swing.JButton jbutton_ThemSP;
    private javax.swing.JButton jbutton_XoaSP;
    private javax.swing.JLabel jlable_HinhThucTT;
    private javax.swing.JLabel jlable_MaDH;
    private javax.swing.JLabel jlable_Search;
    private javax.swing.JPanel jpanel_BangSP;
    private javax.swing.JPanel jpanel_DieuKhien;
    private view.panelBackgpround jpanel_Root;
    private javax.swing.JPanel jpanel_Search;
    private javax.swing.JPanel jpanel_ThanhToan;
    private javax.swing.JRadioButton jradiobutton_ChuyenKhoan;
    private javax.swing.JRadioButton jradiobutton_TienMat;
    private javax.swing.JScrollPane jscrollpane_BangSP;
    private javax.swing.JTable jtable_BangSP;
    private javax.swing.JTextField jtextfield_Search;
    // End of variables declaration//GEN-END:variables
}
