package view.QuanLyDonHang;

import Model.SanPham;
import controller.SanPhamDAO;
import java.awt.Window;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import view.QuanLyDonHang.jframe_ThemDonHang;

/**
 *
 * @author NANG TIEN HANH
 */
public class jframe_ChinhSuaSP extends javax.swing.JFrame {

    private SanPham sanPhamToEdit;
    private jframe_ThemDonHang themDonHangFrame;
    
    public jframe_ChinhSuaSP(jframe_ThemDonHang parent) {
        this.themDonHangFrame = parent;
        this.setLocationRelativeTo(null);
        initComponents();
        jtxt_MaSP.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jtxt_MaSPKeyPressed(evt);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void jtxt_MaSPKeyPressed(java.awt.event.KeyEvent evt) {                                           
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Khi nhấn Enter
            String maSP = jtxt_MaSP.getText();
            if (!maSP.isEmpty()) {
                try {
                    int MaSP = Integer.parseInt(maSP);
                    // Gọi phương thức truy vấn thông tin sản phẩm từ cơ sở dữ liệu
                    SanPhamDAO sanPhamDAO = new SanPhamDAO();
                    SanPham sanPham = sanPhamDAO.layThongTinSanPhamTheoMa(MaSP);
                    if (sanPham != null) {
                        // Nếu sản phẩm tồn tại, hiển thị thông tin lên giao diện
                        jtxt_TenSP.setText(sanPham.getTENSP());
                        jtxt_GiaBan.setText(String.valueOf(sanPham.getGIABAN()));
                        jtxt_DVT.setText(sanPham.getDVT());
                    } else {
                        // Nếu không tìm thấy sản phẩm, thông báo lỗi
                        JOptionPane.showMessageDialog(null, "Không tìm thấy sản phẩm có mã: " + maSP);
                    }
                } catch (NumberFormatException e) {
                    // Nếu nhập không phải số, thông báo lỗi
                    JOptionPane.showMessageDialog(null, "Mã sản phẩm phải là số nguyên.");
                }
            } else {
                // Nếu mã sản phẩm trống, xóa thông tin trên các trường
                jtxt_TenSP.setText("");
                jtxt_GiaBan.setText("");
                jtxt_DVT.setText("");
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_ChinhSuaSP = new javax.swing.JPanel();
        jpanel_ThongTinSua = new javax.swing.JPanel();
        jlabel_MaSP = new javax.swing.JLabel();
        jlabel_TenSP = new javax.swing.JLabel();
        jlabel_DVT = new javax.swing.JLabel();
        jlable_SL = new javax.swing.JLabel();
        jtxt_SL = new javax.swing.JTextField();
        jtxt_TenSP = new javax.swing.JTextField();
        jtxt_MaSP = new javax.swing.JTextField();
        jtxt_DVT = new javax.swing.JTextField();
        jlable_GiaBan = new javax.swing.JLabel();
        jtxt_GiaBan = new javax.swing.JTextField();
        jbtn_Huy = new javax.swing.JButton();
        jbtn_XacNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanel_ChinhSuaSP.setBackground(new java.awt.Color(255, 255, 255));

        jpanel_ThongTinSua.setBackground(new java.awt.Color(255, 255, 255));

        jlabel_MaSP.setFont(new java.awt.Font("UTM Helve", 1, 12)); // NOI18N
        jlabel_MaSP.setText("Mã sản phẩm");

        jlabel_TenSP.setFont(new java.awt.Font("UTM Helve", 1, 12)); // NOI18N
        jlabel_TenSP.setText("Tên sản phẩm");

        jlabel_DVT.setFont(new java.awt.Font("UTM Helve", 1, 12)); // NOI18N
        jlabel_DVT.setText("Đơn vị tính");

        jlable_SL.setFont(new java.awt.Font("UTM Helve", 1, 12)); // NOI18N
        jlable_SL.setText("Số lượng");

        jtxt_SL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtxt_TenSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtxt_MaSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtxt_DVT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlable_GiaBan.setFont(new java.awt.Font("UTM Helve", 1, 12)); // NOI18N
        jlable_GiaBan.setText("Giá bán");

        jtxt_GiaBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_GiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_GiaBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_ThongTinSuaLayout = new javax.swing.GroupLayout(jpanel_ThongTinSua);
        jpanel_ThongTinSua.setLayout(jpanel_ThongTinSuaLayout);
        jpanel_ThongTinSuaLayout.setHorizontalGroup(
            jpanel_ThongTinSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_ThongTinSuaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jpanel_ThongTinSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlable_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_SL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlable_SL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_DVT, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_DVT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jpanel_ThongTinSuaLayout.setVerticalGroup(
            jpanel_ThongTinSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_ThongTinSuaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlabel_MaSP)
                .addGap(6, 6, 6)
                .addComponent(jtxt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlable_SL)
                .addGap(6, 6, 6)
                .addComponent(jtxt_SL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabel_TenSP)
                .addGap(6, 6, 6)
                .addComponent(jtxt_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabel_DVT)
                .addGap(6, 6, 6)
                .addComponent(jtxt_DVT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlable_GiaBan)
                .addGap(6, 6, 6)
                .addComponent(jtxt_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jbtn_Huy.setBackground(new java.awt.Color(236, 227, 214));
        jbtn_Huy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_Huy.setForeground(new java.awt.Color(94, 42, 14));
        jbtn_Huy.setText("Hủy");
        jbtn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_HuyActionPerformed(evt);
            }
        });

        jbtn_XacNhan.setBackground(new java.awt.Color(94, 42, 14));
        jbtn_XacNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_XacNhan.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_XacNhan.setText("Xác nhận");
        jbtn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_XacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_ChinhSuaSPLayout = new javax.swing.GroupLayout(jpanel_ChinhSuaSP);
        jpanel_ChinhSuaSP.setLayout(jpanel_ChinhSuaSPLayout);
        jpanel_ChinhSuaSPLayout.setHorizontalGroup(
            jpanel_ChinhSuaSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_ChinhSuaSPLayout.createSequentialGroup()
                .addGroup(jpanel_ChinhSuaSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_ChinhSuaSPLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jpanel_ThongTinSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_ChinhSuaSPLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jbtn_Huy)
                        .addGap(40, 40, 40)
                        .addComponent(jbtn_XacNhan)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jpanel_ChinhSuaSPLayout.setVerticalGroup(
            jpanel_ChinhSuaSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_ChinhSuaSPLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jpanel_ThongTinSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_ChinhSuaSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Huy)
                    .addComponent(jbtn_XacNhan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_ChinhSuaSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jpanel_ChinhSuaSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_XacNhanActionPerformed
        // TODO add your handling code here:
        SanPham sanPhamMoi = new SanPham();
        
        String maSPStr = jtxt_MaSP.getText();
        String SLStr = jtxt_SL.getText();
        double Gia = Double.parseDouble(jtxt_GiaBan.getText());
        int masp_luu = sanPhamToEdit.getMASP();
        themDonHangFrame.xoaSanPhamKhoiDanhSach(sanPhamToEdit.getMASP());
        
        
        // Kiểm tra trường rỗng
    if (maSPStr.equals("") || SLStr.equals("")){
        JOptionPane.showMessageDialog(jframe_ChinhSuaSP.this, "Bạn cần nhập đủ dữ liệu");
        return;
    }
    
    int maSP = 0;
    int SL = 0;
    boolean isValid = true;

    // Kiểm tra định dạng mã sản phẩm mới nhập
    try {
        maSP = Integer.parseInt(maSPStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(jframe_ChinhSuaSP.this, "Mã sản phẩm không hợp lệ");
        isValid = false;
    }

    // Kiểm tra định dạng số lượng mới nhập
    try {
        SL = Integer.parseInt(SLStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(jframe_ChinhSuaSP.this, "Số lượng không hợp lệ");
        isValid = false;
    } finally {
        if (!isValid) {
            return;
        }
    }

    sanPhamMoi.setMASP(maSP);
    sanPhamMoi.setSOLUONG(SL);
    sanPhamMoi.setTENSP(jtxt_TenSP.getText());
    sanPhamMoi.setDVT(jtxt_DVT.getText());
    sanPhamMoi.setGIABAN(Gia);
    
    // Kiểm tra mã sản phẩm đã tồn tại hay chưa
    if (themDonHangFrame.checkMaSP(maSP) == true) {
        JOptionPane.showMessageDialog(jframe_ChinhSuaSP.this, "Mã sản phẩm mà bạn cập nhật đã tồn tại trong đơn hàng");
        themDonHangFrame.themSanPhamVaoDanhSach(sanPhamToEdit);
    } else {
        themDonHangFrame.themSanPhamVaoDanhSach(sanPhamMoi);
        JOptionPane.showMessageDialog(jframe_ChinhSuaSP.this, "Cập nhật thành công");
        dispose(); // Đóng cửa sổ sau khi cập nhật thành công
    }
    }//GEN-LAST:event_jbtn_XacNhanActionPerformed

    private void jtxt_GiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_GiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_GiaBanActionPerformed

    private void jbtn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_HuyActionPerformed
        // TODO add your handling code here:
        // Lấy cửa sổ cha của cửa sổ hiện tại và đóng nó
            Window window = SwingUtilities.getWindowAncestor(jbtn_Huy);
            window.dispose();
    }//GEN-LAST:event_jbtn_HuyActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(jframe_ChinhSuaSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(jframe_ChinhSuaSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(jframe_ChinhSuaSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(jframe_ChinhSuaSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new jframe_ChinhSuaSP().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_Huy;
    private javax.swing.JButton jbtn_XacNhan;
    private javax.swing.JLabel jlabel_DVT;
    private javax.swing.JLabel jlabel_MaSP;
    private javax.swing.JLabel jlabel_TenSP;
    private javax.swing.JLabel jlable_GiaBan;
    private javax.swing.JLabel jlable_SL;
    private javax.swing.JPanel jpanel_ChinhSuaSP;
    private javax.swing.JPanel jpanel_ThongTinSua;
    private javax.swing.JTextField jtxt_DVT;
    private javax.swing.JTextField jtxt_GiaBan;
    private javax.swing.JTextField jtxt_MaSP;
    private javax.swing.JTextField jtxt_SL;
    private javax.swing.JTextField jtxt_TenSP;
    // End of variables declaration//GEN-END:variables
    public void setSanPhamToEdit(SanPham sanPham) {
        this.sanPhamToEdit = sanPham;
        if (sanPham != null) {
            jtxt_MaSP.setText(String.valueOf(sanPham.getMASP()));
            jtxt_TenSP.setText(sanPham.getTENSP());
            jtxt_DVT.setText(sanPham.getDVT());
            jtxt_GiaBan.setText(String.valueOf(sanPham.getGIABAN()));
            jtxt_SL.setText(String.valueOf(sanPham.getSOLUONG()));
        }
    }
}
